title: Stack Problems
description: My Personal Stack Problems
author: 이상훈
github: https://github.com/digimon1740
about: 그냥 개발을 사랑하는 개발자입니다.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/sanghoon.lee.543908"
    - icon: fa-github
      link: "https://github.com/digimon1740"
#    - icon: fa-stack-exchange
#      link: "#"

share:
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/digimon1740
    - text: XML Feed
      url: /feed.xml

url: "https://digimon1740.github.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
